services:
  - type: web
    name: monthsary-surprise
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://your-app-name.onrender.com
